### ISSUE TITLE
/mt fellow quit causes error

### ISSUE THREAD

**Issue by Starcrusher55** [Mag-nus/Mag-Plugins#16]
every time I do /mt fellow quit ....
<{Mag-Tools}>: Exception caught: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Decal.Interop.Core
   at Decal.Interop.Core.ACHooksClass.FellowshipQuit()
   at Decal.Adapter.Wrappers.HooksWrapper.FellowshipQuit()
   at MagTools.PluginCore.ProcessMTCommand(String mtCommand)
   at MagTools.PluginCore.Current_CommandLineText(Object sender, ChatParserInterceptEventArgs e)
8:34:39 Unknown command: mt

Happens on ACE and GDLE, latest version of Magtools

**Comment by scorpuk** [comment]
Same issue with /mt fellow disband:

13:17:18 <{Mag-Tools}>: Exception caught: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Decal.Interop.Core
   at Decal.Interop.Core.ACHooksClass.FellowshipDisband()
   at Decal.Adapter.Wrappers.HooksWrapper.FellowshipDisband()
   at MagTools.PluginCore.ProcessMTCommand(String mtCommand)
   at MagTools.PluginCore.Current_CommandLineText(Object sender, ChatParserInterceptEventArgs e)
13:17:18 You have disbanded your Fellowship.
13:17:18 Unknown command!

Even after clean reboot.

Thsi is on Reefcull

**Comment by Mag-nus** [comment]
This probably an emulator issue.

mag-tools uses the native decal functionality to perform these actions.

Since i'm pretty sure they worked during retail, this should probably be raised as an issue on the ACE repo.
